steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud run deploy paytraq-cloudrun-service \
          --source=. \
          --region=us-central1 \
          --allow-unauthenticated

options:
  logging: CLOUD_LOGGING_ONLY
